"""Конфигурация приложения для поиска по CSV."""
from typing import Dict

DATASET_CONFIG: Dict[str, Dict] = {
    'glaz_boga': {
        'name': 'БД Глаз Бога',
        'file': 'database/БД Глаз Бога.csv',
        'encoding': None,
        'separator': ',',
        'search_fields': {
            'phone': ['phone'],
            'name': ['username', 'first_name', 'last_name'],
            'email': [],
        },
        'display_fields': ['id', 'username', 'first_name', 'last_name', 'phone'],
    },
    'uralsib_common': {
        'name': 'Общая база Уралсиб',
        'file': 'database/Общ_Уралсиб.csv',
        'encoding': None,
        'separator': ';',
        'columns': [
            'ФИО',
            'Дата рождения',
            'Номер',
        ],
        'has_header': False,
        'search_fields': {
            'phone': ['Номер'],
            'name': ['ФИО'],
            'email': [],
        },
        'display_fields': ['ФИО', 'Номер', 'Дата рождения'],
    },
    'otkritie_2023': {
        'name': 'Открытие 2023',
        'file': 'database/Открытие 2023.csv',
        'encoding': None,
        'separator': ';',
        'columns': [
            'Имя',
            'Отчество',
            'Фамилия',
            'Почта',
            'Страна',
            'Область',
            'Город',
            'Почтовый индекс',
            'Адрес',
            'Улица',
            'Дом',
            'Квартира',
            'Номер',
            'Дата рождения',
        ],
        'has_header': False,
        'search_fields': {
            'phone': ['Номер'],
            'name': ['Имя', 'Отчество', 'Фамилия', 'Город', 'Область'],
            'email': ['Почта'],
        },
        'display_fields': ['Фамилия', 'Имя', 'Отчество', 'Номер', 'Почта', 'Город', 'Область', 'Адрес'],
    },
    'promsvyazbank_legacy': {
        'name': 'ПромсвязьБанк (полная выгрузка)',
        'file': 'database/ПромсвязьБанк.csv',
        'encoding': None,
        'separator': ';',
        'search_fields': {
            'phone': ['Телефон'],
            'name': ['Фамилия', 'Имя', 'Отчество'],
            'email': ['email'],
        },
        'display_fields': ['Фамилия', 'Имя', 'Отчество', 'Телефон', 'email', 'День рождения', 'Пас серия', 'Пас номер'],
    },
    'promsvyazbank_2023': {
        'name': 'ПромсвязьБанк 2023',
        'file': 'database/ПромсвязьБанк_2023.csv',
        'encoding': None,
        'separator': ';',
        'search_fields': {
            'phone': ['Телефон'],
            'name': ['Фамилия', 'Имя', 'Отчество'],
            'email': ['email'],
        },
        'display_fields': ['Фамилия', 'Имя', 'Отчество', 'Телефон', 'email', 'День рождения', 'Пас серия', 'Пас номер'],
    },
    'raiffeisen': {
        'name': 'Райфайзен Банк',
        'file': 'database/Райфайзен Банк.csv',
        'encoding': None,
        'separator': ';',
        'columns': [
            'ID',
            'Клиент',
            'Телефон',
            'Статус',
            'Сумма',
            'Продукт',
        ],
        'has_header': False,
        'search_fields': {
            'phone': ['Телефон'],
            'name': ['Клиент', 'Продукт'],
            'email': [],
        },
        'display_fields': ['ID', 'Телефон', 'Сумма', 'Продукт', 'Статус'],
    },
    'renessans': {
        'name': 'Ренессанс Банк',
        'file': 'database/Ренессанс Банк.csv',
        'encoding': None,
        'separator': ';',
        'columns': [
            'Фамилия',
            'Имя',
            'Отчество',
            'Телефон',
            'Дата рождения',
            'Адрес',
            'Дата обновления',
        ],
        'has_header': False,
        'search_fields': {
            'phone': ['Телефон'],
            'name': ['Фамилия', 'Имя', 'Отчество'],
            'email': [],
        },
        'display_fields': ['Фамилия', 'Имя', 'Отчество', 'Телефон', 'Адрес', 'Дата обновления'],
    },
    'rosselhoz_2023': {
        'name': 'Россельхоз Банк 2023',
        'file': 'database/Россельхоз Банк 2023.csv',
        'encoding': None,
        'separator': ';',
        'columns': [
            'Создано',
            'Фамилия',
            'Имя',
            'Отчество',
            'Пол',
            'Дата рождения',
            'Адрес',
            'Паспорт',
            'Телефон',
        ],
        'has_header': False,
        'search_fields': {
            'phone': ['Телефон'],
            'name': ['Фамилия', 'Имя', 'Отчество'],
            'email': [],
        },
        'display_fields': ['Фамилия', 'Имя', 'Отчество', 'Телефон', 'Адрес', 'Паспорт'],
    },
    'sovcombank': {
        'name': 'СовкомБанк',
        'file': 'database/СовкомБанк.csv',
        'encoding': None,
        'separator': ';',
        'search_fields': {
            'phone': ['Раб. телефон', 'Моб. телефон', 'Дом. телефон'],
            'name': ['ФИО', 'Работодатель'],
            'email': ['Email'],
        },
        'display_fields': ['ФИО', 'Работодатель', 'Раб. телефон', 'Моб. телефон', 'Дом. телефон', 'Email', 'Факт. адрес'],
    },
    'moscow_gibdd': {
        'name': 'Москва ГИБДД (MOSCOW_GIBDD_1.csv)',
        'file': 'database/MOSCOW_GIBDD_1.csv',
        'encoding': None,
        'separator': ';',
        'search_fields': {
            'phone': ['phone'],
            'name': ['fio', 'city', 'car_number'],
            'email': ['other_information'],
        },
        'display_fields': [
            'fio',
            'birthday',
            'city',
            'address_street',
            'phone',
            'other_information',
            'car_number',
            'car_info',
            'VIN',
        ],
    },
}

MAX_RESULTS = 100
PROGRESS_STEP = 100_000
HTML_OUTPUT_DIR = 'reports'

